<?xml version="1.0" encoding="utf-8"?><Database Class="dcZooDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="AContent">
    <Type Name="AContent" InheritanceCode="Content" IsInheritanceDefault="true">
      <Column Name="Id" Type="System.Int32" DbType="Int identity(1,1) not null" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AType" Type="System.String" DbType="varchar(50) NOT NULL" CanBeNull="false" IsDiscriminator="true" />
      <Column Name="Title" Type="System.String" DbType="varchar(50) NOT NULL" CanBeNull="false" />
      <Type Name="AChildFirst" InheritanceCode="First" Modifier="Sealed">
        <Column Name="FirstGen" Type="System.String" DbType="varchar(50)" CanBeNull="true" />
      </Type>
      <Type Name="AChildSecond" InheritanceCode="Second">
        <Column Name="SecondGen" Type="System.String" DbType="varchar(50)" CanBeNull="true" />
      </Type>
    </Type>
  </Table>
</Database>