#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooLinqDBTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class dcZooDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertAContent(AContent instance);
    partial void UpdateAContent(AContent instance);
    partial void DeleteAContent(AContent instance);
    #endregion
		
		public dcZooDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcZooDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcZooDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcZooDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AContent> AContent
		{
			get
			{
				return this.GetTable<AContent>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	[global::System.Data.Linq.Mapping.InheritanceMappingAttribute(Code="Content", Type=typeof(AContent), IsDefault=true)]
	[global::System.Data.Linq.Mapping.InheritanceMappingAttribute(Code="First", Type=typeof(AChildFirst))]
	[global::System.Data.Linq.Mapping.InheritanceMappingAttribute(Code="Second", Type=typeof(AChildSecond))]
	public partial class AContent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id = default(int);
		
		private string _AType;
		
		private string _Title;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnATypeChanging(string value);
    partial void OnATypeChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    #endregion
		
		public AContent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int identity(1,1) not null", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int Id
		{
			get
			{
				return this._Id;
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AType", DbType="varchar(50) NOT NULL", CanBeNull=false, IsDiscriminator=true)]
		public string AType
		{
			get
			{
				return this._AType;
			}
			set
			{
				if ((this._AType != value))
				{
					this.OnATypeChanging(value);
					this.SendPropertyChanging();
					this._AType = value;
					this.SendPropertyChanged("AType");
					this.OnATypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="varchar(50) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public sealed partial class AChildFirst : AContent
	{
		
		private string _FirstGen;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFirstGenChanging(string value);
    partial void OnFirstGenChanged();
    #endregion
		
		public AChildFirst()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstGen", DbType="varchar(50)")]
		public string FirstGen
		{
			get
			{
				return this._FirstGen;
			}
			set
			{
				if ((this._FirstGen != value))
				{
					this.OnFirstGenChanging(value);
					this.SendPropertyChanging();
					this._FirstGen = value;
					this.SendPropertyChanged("FirstGen");
					this.OnFirstGenChanged();
				}
			}
		}
	}
	
	public partial class AChildSecond : AContent
	{
		
		private string _SecondGen;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSecondGenChanging(string value);
    partial void OnSecondGenChanged();
    #endregion
		
		public AChildSecond()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecondGen", DbType="varchar(50)")]
		public string SecondGen
		{
			get
			{
				return this._SecondGen;
			}
			set
			{
				if ((this._SecondGen != value))
				{
					this.OnSecondGenChanging(value);
					this.SendPropertyChanging();
					this._SecondGen = value;
					this.SendPropertyChanged("SecondGen");
					this.OnSecondGenChanged();
				}
			}
		}
	}
}
#pragma warning restore 1591
