<?xml version="1.0" encoding="utf-8"?><Database Name="ZooDb" Class="ZooDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Animal">
    <Type Name="Animal" InheritanceCode="Animal" IsInheritanceDefault="true">
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[From]" Member="From" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Single" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Nickname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Reproduction" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Song" Modifier="Virtual" Type="System.String" DbType="VarChar (255) NOT NULL DEFAULT('')" CanBeNull="false" />
      <Column Name="ContentType" Type="System.String" DbType="VARCHAR(50) NOT NULL" CanBeNull="false" IsDiscriminator="true" />
      <Column Name="Id" Type="System.Int32" DbType="INT IDENTITY(1,1) NOT NULL" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Type Name="Cat" InheritanceCode="Cat" Modifier="Sealed">
        <Column Name="Song" Modifier="Override" Type="System.String" DbType="VarChar (255) NOT NULL DEFAULT('')" CanBeNull="false" />
      </Type>
      <Type Name="Dog" InheritanceCode="Dog" Modifier="Sealed">
        <Column Name="Song" Modifier="Override" Type="System.String" DbType="VarChar (255) NOT NULL DEFAULT('')" CanBeNull="false" />
      </Type>
    </Type>
  </Table>
</Database>